<a href="https://colab.research.google.com/github/ricardoefamilia/CollectionsSet/blob/master/Revisao_30Jan25.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#importar Bibliotecas
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as sm
import seaborn as sns

In [10]:
base = pd.read_csv("https://raw.githubusercontent.com/andfranca/proadi-sus-ciencia-de-dados-ia/refs/heads/main/bases/banco-laboratorio.csv",sep=',')

In [11]:
base.describe()

,IDCOLABORADOR,IDADE,CEP,NIVELEDUCACAO,RENDAMENSAL,ANONAEMPRESA,ANOSMESMAPOSICAO,ANOSDESDEULTIMAPROMOCAO
count,1470.000000,1470.000000,1426.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000
mean,1024.865306,36.923810,9.140252,2.912925,14313.103401,7.008163,4.229252,2.187755
std,602.024335,9.135373,8.065954,1.024165,7117.786044,6.126525,3.623137,3.222430
min,1.000000,18.000000,1.000000,1.000000,2094.000000,0.000000,0.000000,0.000000
25%,491.250000,30.000000,2.000000,2.000000,8047.000000,3.000000,2.000000,0.000000
50%,1020.500000,36.000000,7.000000,3.000000,14235.500000,5.000000,3.000000,1.000000
75%,1555.750000,43.000000,14.000000,4.000000,20461.500000,9.000000,7.000000,3.000000
max,2068.000000,60.000000,29.000000,5.000000,26999.000000,40.000000,18.000000,15.000000

In [12]:
base.head()

,IDCOLABORADOR,IDADE,INSATISTFEITO,STATUSCIVIL,GENERO,NOME,SETOR,CARGO,CEP,NIVELEDUCACAO,FORMACAO,RENDAMENSAL,DESCONTOULTIMAFATURA,ANONAEMPRESA,ANOSMESMAPOSICAO,ANOSDESDEULTIMAPROMOCAO
0,1,41,Sim,Solteiro,Feminino,Maria da Silva,Alimentos,Auditor,1.0,2,Ciencias Sociais,19479,Sim,6,4,0
1,5,33,Nao,Casado,Feminino,Ana Oliveira,Saude,Pesquisador,3.0,4,Ciencias Sociais,23159,Sim,8,7,3
2,10,59,Nao,Casado,Feminino,Juliana Santos,Saude,Tecnico de Laboratorio,3.0,3,Medicina,9964,Sim,1,0,0
3,15,29,Nao,Solteiro,Feminino,Fernanda Costa,Saude,Tecnico de Laboratorio,NaN,2,Ciencias Sociais,12682,Sim,9,5,0
4,20,29,Nao,Divorciado,Feminino,Beatriz Lima,Saude,Diretor de Manufatura,21.0,4,Ciencias Sociais,10195,Nao,10,9,8

In [13]:
base.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   IDCOLABORADOR            1470 non-null   int64
 1   IDADE                    1470 non-null   int64
 2   INSATISTFEITO            1470 non-null   object
 3   STATUSCIVIL              1470 non-null   object
 4   GENERO                   1470 non-null   object
 5   NOME                     1470 non-null   object
 6   SETOR                    1470 non-null   object
 7   CARGO                    1470 non-null   object
 8   CEP                      1426 non-null   float64
 9   NIVELEDUCACAO            1470 non-null   int64
 10  FORMACAO                 1470 non-null   object
 11  RENDAMENSAL              1470 non-null   int64
 12  DESCONTOULTIMAFATURA     1470 non-null   object
 13  ANONAEMPRESA             1470 non-null   int64
 14  ANOSMESMAPOSICAO         1470 non-null   int64
 15  ANOSDESDEULTIMAPROMOCAO  1470 non-null   int64
dtypes: float64(1), int64(7), object(8)
memory usage: 183.9+ KB

In [14]:
base.isna().sum()

IDCOLABORADOR               0
IDADE                       0
INSATISTFEITO               0
STATUSCIVIL                 0
GENERO                      0
NOME                        0
SETOR                       0
CARGO                       0
CEP                        44
NIVELEDUCACAO               0
FORMACAO                    0
RENDAMENSAL                 0
DESCONTOULTIMAFATURA        0
ANONAEMPRESA                0
ANOSMESMAPOSICAO            0
ANOSDESDEULTIMAPROMOCAO     0
dtype: int64

In [15]:
#subset - selecionar pedaços da base de dados para work
base['IDADE']

0       41
1       33
2       59
3       29
4       29
        ..
1465    36
1466    39
1467    27
1468    49
1469    34
Name: IDADE, Length: 1470, dtype: int64

In [16]:
#subset de mais de uma coluna
base[['IDADE','STATUSCIVIL']]

      IDADE STATUSCIVIL
0        41    Solteiro
1        33      Casado
2        59      Casado
3        29    Solteiro
4        29  Divorciado
...     ...         ...
1465     36      Casado
1466     39      Casado
1467     27      Casado
1468     49      Casado
1469     34      Casado

[1470 rows x 2 columns]

In [17]:
#working utilizando operadores
base[(base['IDADE']>30)&
     (base['STATUSCIVIL']=='Casado')&
     (base['INSATISTFEITO']=='Sim')
     ]

,IDCOLABORADOR,IDADE,INSATISTFEITO,STATUSCIVIL,GENERO,NOME,SETOR,CARGO,CEP,NIVELEDUCACAO,FORMACAO,RENDAMENSAL,DESCONTOULTIMAFATURA,ANONAEMPRESA,ANOSMESMAPOSICAO,ANOSDESDEULTIMAPROMOCAO
18,58,41,Sim,Casado,Feminino,Priscila Pereira,Saude,Diretor de Pesquisa,12.0,3,Formacao Tecnica,16280,Nao,22,15,15
46,161,56,Sim,Casado,Feminino,Vanessa Carvalho,Saude,Pesquisador,14.0,4,Ciencias Sociais,4510,Sim,5,4,4
48,165,58,Sim,Casado,Feminino,Amanda Goncalves,Saude,Representante da Saude,23.0,4,Medicina,3465,Nao,40,10,15
52,175,31,Sim,Casado,Feminino,Ana Pereira,Alimentos,Auditor,20.0,3,Ciencias Sociais,24788,Sim,2,2,2
96,328,33,Sim,Casado,Feminino,Patricia Oliveira,Saude,Tecnico de Laboratorio,2.0,2,Ciencias Sociais,21509,Nao,9,7,1
126,445,39,Sim,Casado,Feminino,Tatiane Carvalho,Alimentos,Auditor,3.0,2,Medicina,17778,Sim,1,0,0
203,684,45,Sim,Casado,Feminino,Fernanda Costa,Alimentos,Auditor,26.0,4,Ciencias Sociais,5630,Nao,1,1,0
247,840,49,Sim,Casado,Feminino,Bruna Almeida,Alimentos,Auditor,11.0,3,Marketing,5860,Nao,9,8,7
306,1033,37,Sim,Casado,Feminino,Leticia Oliveira,Saude,Representante da Saude,11.0,2,Medicina,14382,Nao,1,0,0
308,1038,52,Sim,Casado,Feminino,Valentina Martins,Alimentos,Gestor,2.0,1,Marketing,25846,Nao,32,14,6
380,1295,44,Sim,Casado,Feminino,Fernanda Alves,Saude,Representante da Saude,15.0,3,Medicina,14075,Nao,10,7,0
399,1360,58,Sim,Casado,Feminino,Priscila Pereira,Saude,Diretor de Manufatura,7.0,4,Medicina,12023,Sim,10,9,5
408,1380,35,Sim,Casado,Feminino,Daniela Silva,Alimentos,Auditor,18.0,4,Marketing,23288,Sim,4,2,3
434,1467,34,Sim,Casado,Feminino,Luana Almeida,Medicamentos,Tecnico de TI,9.0,4,Formacao Tecnica,3072,Nao,2,2,2
454,1572,53,Sim,Casado,Feminino,Rafaela Santos,Saude,Diretor de Manufatura,2.0,5,Formacao Tecnica,14618,Nao,33,7,1
494,1691,48,Sim,Casado,Feminino,Michele Almeida,Alimentos,Representante de Setor,7.0,2,Medicina,11740,Sim,9,7,7
523,1821,46,Sim,Casado,Feminino,Luana Oliveira,Saude,Representante da Saude,21.0,2,Medicina,10842,Nao,9,7,3
539,1869,46,Sim,Casado,Feminino,Priscila Pereira,Alimentos,Auditor,10.0,3,Ciencias Sociais,14011,Nao,8,7,0
609,42,39,Sim,Casado,Masculino,Anselmo Souza,Alimentos,Representante de Setor,NaN,3,Formacao Tecnica,3335,Nao,1,0,0
611,47,50,Sim,Casado,Masculino,Antônio Oliveira,Alimentos,Representante de Setor,3.0,2,Marketing,3810,Sim,3,2,0
629,90,36,Sim,Casado,Masculino,Cicero Dias,Saude,Pesquisador,9.0,3,Medicina,21777,Sim,1,0,0
665,163,31,Sim,Casado,Masculino,Genaro Rodrigues,Alimentos,Auditor,6.0,4,Ciencias Sociais,20739,Sim,7,7,7
700,261,35,Sim,Casado,Masculino,Marinheiro Dias,Saude,Diretor de Manufatura,23.0,2,Ciencias Sociais,15497,Sim,1,0,0
710,282,38,Sim,Casado,Masculino,Nathan Nunes,Saude,Representante da Saude,29.0,1,Medicina,11354,Sim,1,0,0
714,291,32,Sim,Casado,Masculino,Olavo Costa,Alimentos,Auditor,4.0,4,Medicina,25812,Nao,14,8,9
727,325,33,Sim,Casado,Masculino,Ranieri Nunes,Saude,Tecnico de Laboratorio,14.0,3,Medicina,22149,Sim,5,4,0
753,376,47,Sim,Casado,Masculino,Victor Barros,Saude,Gestor,29.0,4,Ciencias Sociais,10268,Sim,10,7,9
784,433,52,Sim,Casado,Masculino,Bernardo Jose Ferreira,Saude,Pesquisador,8.0,4,Medicina,17747,Nao,8,2,7
812,492,40,Sim,Casado,Masculino,Edmilson Costa,Alimentos,Auditor,22.0,2,Marketing,6110,Sim,6,4,1
845,582,33,Sim,Casado,Masculino,Joaquim Nunes,Saude,Gestor,15.0,1,Medicina,24619,Sim,7,6,7
849,587,31,Sim,Casado,Masculino,Jose Roberto Barros,Saude,Representante da Saude,20.0,3,Ciencias Sociais,22908,Nao,1,0,0
867,631,32,Sim,Casado,Masculino,Enzo Nunes,Alimentos,Auditor,11.0,4,Outros,23914,Nao,4,2,1
905,723,50,Sim,Casado,Masculino,Gael Rodrigues,Alimentos,Auditor,8.0,2,Formacao Tecnica,23452,Sim,4,3,1
930,787,55,Sim,Casado,Masculino,Gael Barros,Saude,Gestor,2.0,3,Medicina,21199,Sim,5,2,1
984,932,39,Sim,Casado,Masculino,Gael Nunes,Saude,Tecnico de Laboratorio,6.0,3,Medicina,4303,Sim,2,2,2
998,967,36,Sim,Casado,Masculino,Nicolas Teixeira,Alimentos,Auditor,3.0,1,Ciencias Sociais,5518,Sim,16,7,3
999,970,37,Sim,Casado,Masculino,Otavio Dias,Alimentos,Auditor,1.0,4,Ciencias Sociais,14922,Nao,14,1,11
1041,1081,51,Sim,Casado,Masculino,Miguel Martins,Saude,Pesquisador,4.0,4,Ciencias Sociais,10332,Sim,10,0,2
1048,1098,44,Sim,Casado,Masculino,Ravi Silva,Medicamentos,Tecnico de TI,1.0,2,Medicina,2326,Nao,20,6,3
1080,1160,31,Sim,Casado,Masculino,Ravi Oliveira,Saude,Tecnico de Laboratorio,15.0,3,Medicina,6233,Nao,2,2,2
1140,1309,32,Sim,Casado,Masculino,Heitor Dias,Saude,Tecnico de Laboratorio,7.0,2,Ciencias Sociais,22845,Nao,10,4,1
1146,1333,44,Sim,Casado,Masculino,Valentin Martins,Saude,Tecnico de Laboratorio,3.0,3,Ciencias Sociais,14669,Nao,3,2,1
1163,1389,31,Sim,Casado,Masculino,Lorenzo Barros,Saude,Diretor de Manufatura,22.0,4,Medicina,21057,Sim,10,2,6
1190,1464,31,Sim,Casado,Masculino,Ravi Rodrigues,Saude,Tecnico de Laboratorio,2.0,3,Ciencias Sociais,21081,Sim,2,2,2
1245,1573,38,Sim,Casado,Masculino,Miguel Teixeira,Saude,Diretor de Manufatura,2.0,3,Medicina,7653,Nao,5,2,1
1275,1639,35,Sim,Casado,Masculino,Henrique Ferreira,Alimentos,Auditor,10.0,3,Medicina,21530,Nao,13,12,6
1312,1716,47,Sim,Casado,Masculino,Nicolas Teixeira,Alimentos,Auditor,9.0,3,Ciencias Sociais,24164,Nao,23,5,14
1333,1761,31,Sim,Casado,Masculino,Miguel Martins,Alimentos,Auditor,16.0,4,Marketing,19002,Nao,1,0,0
1337,1767,43,Sim,Casado,Masculino,Ravi Santos,Saude,Pesquisador,17.0,3,Formacao Tecnica,15587,Sim,1,0,0
1358,1807,34,Sim,Casado,Masculino,Caio Mendes,Saude,Tecnico de Laboratorio,9.0,4,Ciencias Sociais,6208,Nao,7,1,0
1368,1842,31,Sim,Casado,Masculino,Ravi Rodrigues,Medicamentos,Tecnico de TI,18.0,5,Recursos Humanos,21495,Nao,1,0,0
1393,1905,34,Sim,Casado,Masculino,Gabriel Oliveira,Saude,Pesquisador,16.0,4,Formacao Tecnica,14460,Sim,5,2,3
1422,1967,31,Sim,Casado,Masculino,Pedro Santos,Alimentos,Auditor,26.0,4,Marketing,21075,Sim,10,7,0
1455,2032,56,Sim,Casado,Masculino,Pedro Barros,Saude,Tecnico de Laboratorio,7.0,2,Formacao Tecnica,3666,Nao,10,9,9

In [19]:
#filtrando apresentando colunas desejadas
base_filtrada = base[(base['IDADE']>30)&
     (base['STATUSCIVIL']=='Casado')&
     (base['INSATISTFEITO']=='Sim')
     ]

base_filtrada

,IDCOLABORADOR,IDADE,INSATISTFEITO,STATUSCIVIL,GENERO,NOME,SETOR,CARGO,CEP,NIVELEDUCACAO,FORMACAO,RENDAMENSAL,DESCONTOULTIMAFATURA,ANONAEMPRESA,ANOSMESMAPOSICAO,ANOSDESDEULTIMAPROMOCAO
18,58,41,Sim,Casado,Feminino,Priscila Pereira,Saude,Diretor de Pesquisa,12.0,3,Formacao Tecnica,16280,Nao,22,15,15
46,161,56,Sim,Casado,Feminino,Vanessa Carvalho,Saude,Pesquisador,14.0,4,Ciencias Sociais,4510,Sim,5,4,4
48,165,58,Sim,Casado,Feminino,Amanda Goncalves,Saude,Representante da Saude,23.0,4,Medicina,3465,Nao,40,10,15
52,175,31,Sim,Casado,Feminino,Ana Pereira,Alimentos,Auditor,20.0,3,Ciencias Sociais,24788,Sim,2,2,2
96,328,33,Sim,Casado,Feminino,Patricia Oliveira,Saude,Tecnico de Laboratorio,2.0,2,Ciencias Sociais,21509,Nao,9,7,1
126,445,39,Sim,Casado,Feminino,Tatiane Carvalho,Alimentos,Auditor,3.0,2,Medicina,17778,Sim,1,0,0
203,684,45,Sim,Casado,Feminino,Fernanda Costa,Alimentos,Auditor,26.0,4,Ciencias Sociais,5630,Nao,1,1,0
247,840,49,Sim,Casado,Feminino,Bruna Almeida,Alimentos,Auditor,11.0,3,Marketing,5860,Nao,9,8,7
306,1033,37,Sim,Casado,Feminino,Leticia Oliveira,Saude,Representante da Saude,11.0,2,Medicina,14382,Nao,1,0,0
308,1038,52,Sim,Casado,Feminino,Valentina Martins,Alimentos,Gestor,2.0,1,Marketing,25846,Nao,32,14,6
380,1295,44,Sim,Casado,Feminino,Fernanda Alves,Saude,Representante da Saude,15.0,3,Medicina,14075,Nao,10,7,0
399,1360,58,Sim,Casado,Feminino,Priscila Pereira,Saude,Diretor de Manufatura,7.0,4,Medicina,12023,Sim,10,9,5
408,1380,35,Sim,Casado,Feminino,Daniela Silva,Alimentos,Auditor,18.0,4,Marketing,23288,Sim,4,2,3
434,1467,34,Sim,Casado,Feminino,Luana Almeida,Medicamentos,Tecnico de TI,9.0,4,Formacao Tecnica,3072,Nao,2,2,2
454,1572,53,Sim,Casado,Feminino,Rafaela Santos,Saude,Diretor de Manufatura,2.0,5,Formacao Tecnica,14618,Nao,33,7,1
494,1691,48,Sim,Casado,Feminino,Michele Almeida,Alimentos,Representante de Setor,7.0,2,Medicina,11740,Sim,9,7,7
523,1821,46,Sim,Casado,Feminino,Luana Oliveira,Saude,Representante da Saude,21.0,2,Medicina,10842,Nao,9,7,3
539,1869,46,Sim,Casado,Feminino,Priscila Pereira,Alimentos,Auditor,10.0,3,Ciencias Sociais,14011,Nao,8,7,0
609,42,39,Sim,Casado,Masculino,Anselmo Souza,Alimentos,Representante de Setor,NaN,3,Formacao Tecnica,3335,Nao,1,0,0
611,47,50,Sim,Casado,Masculino,Antônio Oliveira,Alimentos,Representante de Setor,3.0,2,Marketing,3810,Sim,3,2,0
629,90,36,Sim,Casado,Masculino,Cicero Dias,Saude,Pesquisador,9.0,3,Medicina,21777,Sim,1,0,0
665,163,31,Sim,Casado,Masculino,Genaro Rodrigues,Alimentos,Auditor,6.0,4,Ciencias Sociais,20739,Sim,7,7,7
700,261,35,Sim,Casado,Masculino,Marinheiro Dias,Saude,Diretor de Manufatura,23.0,2,Ciencias Sociais,15497,Sim,1,0,0
710,282,38,Sim,Casado,Masculino,Nathan Nunes,Saude,Representante da Saude,29.0,1,Medicina,11354,Sim,1,0,0
714,291,32,Sim,Casado,Masculino,Olavo Costa,Alimentos,Auditor,4.0,4,Medicina,25812,Nao,14,8,9
727,325,33,Sim,Casado,Masculino,Ranieri Nunes,Saude,Tecnico de Laboratorio,14.0,3,Medicina,22149,Sim,5,4,0
753,376,47,Sim,Casado,Masculino,Victor Barros,Saude,Gestor,29.0,4,Ciencias Sociais,10268,Sim,10,7,9
784,433,52,Sim,Casado,Masculino,Bernardo Jose Ferreira,Saude,Pesquisador,8.0,4,Medicina,17747,Nao,8,2,7
812,492,40,Sim,Casado,Masculino,Edmilson Costa,Alimentos,Auditor,22.0,2,Marketing,6110,Sim,6,4,1
845,582,33,Sim,Casado,Masculino,Joaquim Nunes,Saude,Gestor,15.0,1,Medicina,24619,Sim,7,6,7
849,587,31,Sim,Casado,Masculino,Jose Roberto Barros,Saude,Representante da Saude,20.0,3,Ciencias Sociais,22908,Nao,1,0,0
867,631,32,Sim,Casado,Masculino,Enzo Nunes,Alimentos,Auditor,11.0,4,Outros,23914,Nao,4,2,1
905,723,50,Sim,Casado,Masculino,Gael Rodrigues,Alimentos,Auditor,8.0,2,Formacao Tecnica,23452,Sim,4,3,1
930,787,55,Sim,Casado,Masculino,Gael Barros,Saude,Gestor,2.0,3,Medicina,21199,Sim,5,2,1
984,932,39,Sim,Casado,Masculino,Gael Nunes,Saude,Tecnico de Laboratorio,6.0,3,Medicina,4303,Sim,2,2,2
998,967,36,Sim,Casado,Masculino,Nicolas Teixeira,Alimentos,Auditor,3.0,1,Ciencias Sociais,5518,Sim,16,7,3
999,970,37,Sim,Casado,Masculino,Otavio Dias,Alimentos,Auditor,1.0,4,Ciencias Sociais,14922,Nao,14,1,11
1041,1081,51,Sim,Casado,Masculino,Miguel Martins,Saude,Pesquisador,4.0,4,Ciencias Sociais,10332,Sim,10,0,2
1048,1098,44,Sim,Casado,Masculino,Ravi Silva,Medicamentos,Tecnico de TI,1.0,2,Medicina,2326,Nao,20,6,3
1080,1160,31,Sim,Casado,Masculino,Ravi Oliveira,Saude,Tecnico de Laboratorio,15.0,3,Medicina,6233,Nao,2,2,2
1140,1309,32,Sim,Casado,Masculino,Heitor Dias,Saude,Tecnico de Laboratorio,7.0,2,Ciencias Sociais,22845,Nao,10,4,1
1146,1333,44,Sim,Casado,Masculino,Valentin Martins,Saude,Tecnico de Laboratorio,3.0,3,Ciencias Sociais,14669,Nao,3,2,1
1163,1389,31,Sim,Casado,Masculino,Lorenzo Barros,Saude,Diretor de Manufatura,22.0,4,Medicina,21057,Sim,10,2,6
1190,1464,31,Sim,Casado,Masculino,Ravi Rodrigues,Saude,Tecnico de Laboratorio,2.0,3,Ciencias Sociais,21081,Sim,2,2,2
1245,1573,38,Sim,Casado,Masculino,Miguel Teixeira,Saude,Diretor de Manufatura,2.0,3,Medicina,7653,Nao,5,2,1
1275,1639,35,Sim,Casado,Masculino,Henrique Ferreira,Alimentos,Auditor,10.0,3,Medicina,21530,Nao,13,12,6
1312,1716,47,Sim,Casado,Masculino,Nicolas Teixeira,Alimentos,Auditor,9.0,3,Ciencias Sociais,24164,Nao,23,5,14
1333,1761,31,Sim,Casado,Masculino,Miguel Martins,Alimentos,Auditor,16.0,4,Marketing,19002,Nao,1,0,0
1337,1767,43,Sim,Casado,Masculino,Ravi Santos,Saude,Pesquisador,17.0,3,Formacao Tecnica,15587,Sim,1,0,0
1358,1807,34,Sim,Casado,Masculino,Caio Mendes,Saude,Tecnico de Laboratorio,9.0,4,Ciencias Sociais,6208,Nao,7,1,0
1368,1842,31,Sim,Casado,Masculino,Ravi Rodrigues,Medicamentos,Tecnico de TI,18.0,5,Recursos Humanos,21495,Nao,1,0,0
1393,1905,34,Sim,Casado,Masculino,Gabriel Oliveira,Saude,Pesquisador,16.0,4,Formacao Tecnica,14460,Sim,5,2,3
1422,1967,31,Sim,Casado,Masculino,Pedro Santos,Alimentos,Auditor,26.0,4,Marketing,21075,Sim,10,7,0
1455,2032,56,Sim,Casado,Masculino,Pedro Barros,Saude,Tecnico de Laboratorio,7.0,2,Formacao Tecnica,3666,Nao,10,9,9

In [21]:
base_filtrada[['IDADE','STATUSCIVIL','STATUSCIVIL']]

      IDADE STATUSCIVIL STATUSCIVIL
18       41      Casado      Casado
46       56      Casado      Casado
48       58      Casado      Casado
52       31      Casado      Casado
96       33      Casado      Casado
126      39      Casado      Casado
203      45      Casado      Casado
247      49      Casado      Casado
306      37      Casado      Casado
308      52      Casado      Casado
380      44      Casado      Casado
399      58      Casado      Casado
408      35      Casado      Casado
434      34      Casado      Casado
454      53      Casado      Casado
494      48      Casado      Casado
523      46      Casado      Casado
539      46      Casado      Casado
609      39      Casado      Casado
611      50      Casado      Casado
629      36      Casado      Casado
665      31      Casado      Casado
700      35      Casado      Casado
710      38      Casado      Casado
714      32      Casado      Casado
727      33      Casado      Casado
753      47      Casado      Casado
784      52      Casado      Casado
812      40      Casado      Casado
845      33      Casado      Casado
849      31      Casado      Casado
867      32      Casado      Casado
905      50      Casado      Casado
930      55      Casado      Casado
984      39      Casado      Casado
998      36      Casado      Casado
999      37      Casado      Casado
1041     51      Casado      Casado
1048     44      Casado      Casado
1080     31      Casado      Casado
1140     32      Casado      Casado
1146     44      Casado      Casado
1163     31      Casado      Casado
1190     31      Casado      Casado
1245     38      Casado      Casado
1275     35      Casado      Casado
1312     47      Casado      Casado
1333     31      Casado      Casado
1337     43      Casado      Casado
1358     34      Casado      Casado
1368     31      Casado      Casado
1393     34      Casado      Casado
1422     31      Casado      Casado
1455     56      Casado      Casado

In [ ]:
#DELETAR UMA VARIÁVEL (OBJETO)
#del base (por exemplo)

In [27]:
#Resetar o índice
base_filtrada.reset_index(inplace=True,drop=True)

,IDCOLABORADOR,IDADE,INSATISTFEITO,STATUSCIVIL,GENERO,NOME,SETOR,CARGO,CEP,NIVELEDUCACAO,FORMACAO,RENDAMENSAL,DESCONTOULTIMAFATURA,ANONAEMPRESA,ANOSMESMAPOSICAO,ANOSDESDEULTIMAPROMOCAO
0,58,41,Sim,Casado,Feminino,Priscila Pereira,Saude,Diretor de Pesquisa,12.0,3,Formacao Tecnica,16280,Nao,22,15,15
1,161,56,Sim,Casado,Feminino,Vanessa Carvalho,Saude,Pesquisador,14.0,4,Ciencias Sociais,4510,Sim,5,4,4
2,165,58,Sim,Casado,Feminino,Amanda Goncalves,Saude,Representante da Saude,23.0,4,Medicina,3465,Nao,40,10,15
3,175,31,Sim,Casado,Feminino,Ana Pereira,Alimentos,Auditor,20.0,3,Ciencias Sociais,24788,Sim,2,2,2
4,328,33,Sim,Casado,Feminino,Patricia Oliveira,Saude,Tecnico de Laboratorio,2.0,2,Ciencias Sociais,21509,Nao,9,7,1
5,445,39,Sim,Casado,Feminino,Tatiane Carvalho,Alimentos,Auditor,3.0,2,Medicina,17778,Sim,1,0,0
6,684,45,Sim,Casado,Feminino,Fernanda Costa,Alimentos,Auditor,26.0,4,Ciencias Sociais,5630,Nao,1,1,0
7,840,49,Sim,Casado,Feminino,Bruna Almeida,Alimentos,Auditor,11.0,3,Marketing,5860,Nao,9,8,7
8,1033,37,Sim,Casado,Feminino,Leticia Oliveira,Saude,Representante da Saude,11.0,2,Medicina,14382,Nao,1,0,0
9,1038,52,Sim,Casado,Feminino,Valentina Martins,Alimentos,Gestor,2.0,1,Marketing,25846,Nao,32,14,6
10,1295,44,Sim,Casado,Feminino,Fernanda Alves,Saude,Representante da Saude,15.0,3,Medicina,14075,Nao,10,7,0
11,1360,58,Sim,Casado,Feminino,Priscila Pereira,Saude,Diretor de Manufatura,7.0,4,Medicina,12023,Sim,10,9,5
12,1380,35,Sim,Casado,Feminino,Daniela Silva,Alimentos,Auditor,18.0,4,Marketing,23288,Sim,4,2,3
13,1467,34,Sim,Casado,Feminino,Luana Almeida,Medicamentos,Tecnico de TI,9.0,4,Formacao Tecnica,3072,Nao,2,2,2
14,1572,53,Sim,Casado,Feminino,Rafaela Santos,Saude,Diretor de Manufatura,2.0,5,Formacao Tecnica,14618,Nao,33,7,1
15,1691,48,Sim,Casado,Feminino,Michele Almeida,Alimentos,Representante de Setor,7.0,2,Medicina,11740,Sim,9,7,7
16,1821,46,Sim,Casado,Feminino,Luana Oliveira,Saude,Representante da Saude,21.0,2,Medicina,10842,Nao,9,7,3
17,1869,46,Sim,Casado,Feminino,Priscila Pereira,Alimentos,Auditor,10.0,3,Ciencias Sociais,14011,Nao,8,7,0
18,42,39,Sim,Casado,Masculino,Anselmo Souza,Alimentos,Representante de Setor,NaN,3,Formacao Tecnica,3335,Nao,1,0,0
19,47,50,Sim,Casado,Masculino,Antônio Oliveira,Alimentos,Representante de Setor,3.0,2,Marketing,3810,Sim,3,2,0
20,90,36,Sim,Casado,Masculino,Cicero Dias,Saude,Pesquisador,9.0,3,Medicina,21777,Sim,1,0,0
21,163,31,Sim,Casado,Masculino,Genaro Rodrigues,Alimentos,Auditor,6.0,4,Ciencias Sociais,20739,Sim,7,7,7
22,261,35,Sim,Casado,Masculino,Marinheiro Dias,Saude,Diretor de Manufatura,23.0,2,Ciencias Sociais,15497,Sim,1,0,0
23,282,38,Sim,Casado,Masculino,Nathan Nunes,Saude,Representante da Saude,29.0,1,Medicina,11354,Sim,1,0,0
24,291,32,Sim,Casado,Masculino,Olavo Costa,Alimentos,Auditor,4.0,4,Medicina,25812,Nao,14,8,9
25,325,33,Sim,Casado,Masculino,Ranieri Nunes,Saude,Tecnico de Laboratorio,14.0,3,Medicina,22149,Sim,5,4,0
26,376,47,Sim,Casado,Masculino,Victor Barros,Saude,Gestor,29.0,4,Ciencias Sociais,10268,Sim,10,7,9
27,433,52,Sim,Casado,Masculino,Bernardo Jose Ferreira,Saude,Pesquisador,8.0,4,Medicina,17747,Nao,8,2,7
28,492,40,Sim,Casado,Masculino,Edmilson Costa,Alimentos,Auditor,22.0,2,Marketing,6110,Sim,6,4,1
29,582,33,Sim,Casado,Masculino,Joaquim Nunes,Saude,Gestor,15.0,1,Medicina,24619,Sim,7,6,7
30,587,31,Sim,Casado,Masculino,Jose Roberto Barros,Saude,Representante da Saude,20.0,3,Ciencias Sociais,22908,Nao,1,0,0
31,631,32,Sim,Casado,Masculino,Enzo Nunes,Alimentos,Auditor,11.0,4,Outros,23914,Nao,4,2,1
32,723,50,Sim,Casado,Masculino,Gael Rodrigues,Alimentos,Auditor,8.0,2,Formacao Tecnica,23452,Sim,4,3,1
33,787,55,Sim,Casado,Masculino,Gael Barros,Saude,Gestor,2.0,3,Medicina,21199,Sim,5,2,1
34,932,39,Sim,Casado,Masculino,Gael Nunes,Saude,Tecnico de Laboratorio,6.0,3,Medicina,4303,Sim,2,2,2
35,967,36,Sim,Casado,Masculino,Nicolas Teixeira,Alimentos,Auditor,3.0,1,Ciencias Sociais,5518,Sim,16,7,3
36,970,37,Sim,Casado,Masculino,Otavio Dias,Alimentos,Auditor,1.0,4,Ciencias Sociais,14922,Nao,14,1,11
37,1081,51,Sim,Casado,Masculino,Miguel Martins,Saude,Pesquisador,4.0,4,Ciencias Sociais,10332,Sim,10,0,2
38,1098,44,Sim,Casado,Masculino,Ravi Silva,Medicamentos,Tecnico de TI,1.0,2,Medicina,2326,Nao,20,6,3
39,1160,31,Sim,Casado,Masculino,Ravi Oliveira,Saude,Tecnico de Laboratorio,15.0,3,Medicina,6233,Nao,2,2,2
40,1309,32,Sim,Casado,Masculino,Heitor Dias,Saude,Tecnico de Laboratorio,7.0,2,Ciencias Sociais,22845,Nao,10,4,1
41,1333,44,Sim,Casado,Masculino,Valentin Martins,Saude,Tecnico de Laboratorio,3.0,3,Ciencias Sociais,14669,Nao,3,2,1
42,1389,31,Sim,Casado,Masculino,Lorenzo Barros,Saude,Diretor de Manufatura,22.0,4,Medicina,21057,Sim,10,2,6
43,1464,31,Sim,Casado,Masculino,Ravi Rodrigues,Saude,Tecnico de Laboratorio,2.0,3,Ciencias Sociais,21081,Sim,2,2,2
44,1573,38,Sim,Casado,Masculino,Miguel Teixeira,Saude,Diretor de Manufatura,2.0,3,Medicina,7653,Nao,5,2,1
45,1639,35,Sim,Casado,Masculino,Henrique Ferreira,Alimentos,Auditor,10.0,3,Medicina,21530,Nao,13,12,6
46,1716,47,Sim,Casado,Masculino,Nicolas Teixeira,Alimentos,Auditor,9.0,3,Ciencias Sociais,24164,Nao,23,5,14
47,1761,31,Sim,Casado,Masculino,Miguel Martins,Alimentos,Auditor,16.0,4,Marketing,19002,Nao,1,0,0
48,1767,43,Sim,Casado,Masculino,Ravi Santos,Saude,Pesquisador,17.0,3,Formacao Tecnica,15587,Sim,1,0,0
49,1807,34,Sim,Casado,Masculino,Caio Mendes,Saude,Tecnico de Laboratorio,9.0,4,Ciencias Sociais,6208,Nao,7,1,0
50,1842,31,Sim,Casado,Masculino,Ravi Rodrigues,Medicamentos,Tecnico de TI,18.0,5,Recursos Humanos,21495,Nao,1,0,0
51,1905,34,Sim,Casado,Masculino,Gabriel Oliveira,Saude,Pesquisador,16.0,4,Formacao Tecnica,14460,Sim,5,2,3
52,1967,31,Sim,Casado,Masculino,Pedro Santos,Alimentos,Auditor,26.0,4,Marketing,21075,Sim,10,7,0
53,2032,56,Sim,Casado,Masculino,Pedro Barros,Saude,Tecnico de Laboratorio,7.0,2,Formacao Tecnica,3666,Nao,10,9,9

In [28]:
#Criando um novo arquivo csv clonado da base filtrada, por exemplo
base_filtrada.to_csv('base_filtrada.csv',index=False,sep=";", decimal=",")

In [29]:
#Criando uma nova coluna na base, exemplo
base_filtrada['coluna_nova'] = 0

<ipython-input-29-25a17a46043d>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base_filtrada['coluna_nova'] = 0

In [31]:
base_filtrada

,IDCOLABORADOR,IDADE,INSATISTFEITO,STATUSCIVIL,GENERO,NOME,SETOR,CARGO,CEP,NIVELEDUCACAO,FORMACAO,RENDAMENSAL,DESCONTOULTIMAFATURA,ANONAEMPRESA,ANOSMESMAPOSICAO,ANOSDESDEULTIMAPROMOCAO,coluna_nova
0,58,41,Sim,Casado,Feminino,Priscila Pereira,Saude,Diretor de Pesquisa,12.0,3,Formacao Tecnica,16280,Nao,22,15,15,0
1,161,56,Sim,Casado,Feminino,Vanessa Carvalho,Saude,Pesquisador,14.0,4,Ciencias Sociais,4510,Sim,5,4,4,0
2,165,58,Sim,Casado,Feminino,Amanda Goncalves,Saude,Representante da Saude,23.0,4,Medicina,3465,Nao,40,10,15,0
3,175,31,Sim,Casado,Feminino,Ana Pereira,Alimentos,Auditor,20.0,3,Ciencias Sociais,24788,Sim,2,2,2,0
4,328,33,Sim,Casado,Feminino,Patricia Oliveira,Saude,Tecnico de Laboratorio,2.0,2,Ciencias Sociais,21509,Nao,9,7,1,0
5,445,39,Sim,Casado,Feminino,Tatiane Carvalho,Alimentos,Auditor,3.0,2,Medicina,17778,Sim,1,0,0,0
6,684,45,Sim,Casado,Feminino,Fernanda Costa,Alimentos,Auditor,26.0,4,Ciencias Sociais,5630,Nao,1,1,0,0
7,840,49,Sim,Casado,Feminino,Bruna Almeida,Alimentos,Auditor,11.0,3,Marketing,5860,Nao,9,8,7,0
8,1033,37,Sim,Casado,Feminino,Leticia Oliveira,Saude,Representante da Saude,11.0,2,Medicina,14382,Nao,1,0,0,0
9,1038,52,Sim,Casado,Feminino,Valentina Martins,Alimentos,Gestor,2.0,1,Marketing,25846,Nao,32,14,6,0
10,1295,44,Sim,Casado,Feminino,Fernanda Alves,Saude,Representante da Saude,15.0,3,Medicina,14075,Nao,10,7,0,0
11,1360,58,Sim,Casado,Feminino,Priscila Pereira,Saude,Diretor de Manufatura,7.0,4,Medicina,12023,Sim,10,9,5,0
12,1380,35,Sim,Casado,Feminino,Daniela Silva,Alimentos,Auditor,18.0,4,Marketing,23288,Sim,4,2,3,0
13,1467,34,Sim,Casado,Feminino,Luana Almeida,Medicamentos,Tecnico de TI,9.0,4,Formacao Tecnica,3072,Nao,2,2,2,0
14,1572,53,Sim,Casado,Feminino,Rafaela Santos,Saude,Diretor de Manufatura,2.0,5,Formacao Tecnica,14618,Nao,33,7,1,0
15,1691,48,Sim,Casado,Feminino,Michele Almeida,Alimentos,Representante de Setor,7.0,2,Medicina,11740,Sim,9,7,7,0
16,1821,46,Sim,Casado,Feminino,Luana Oliveira,Saude,Representante da Saude,21.0,2,Medicina,10842,Nao,9,7,3,0
17,1869,46,Sim,Casado,Feminino,Priscila Pereira,Alimentos,Auditor,10.0,3,Ciencias Sociais,14011,Nao,8,7,0,0
18,42,39,Sim,Casado,Masculino,Anselmo Souza,Alimentos,Representante de Setor,NaN,3,Formacao Tecnica,3335,Nao,1,0,0,0
19,47,50,Sim,Casado,Masculino,Antônio Oliveira,Alimentos,Representante de Setor,3.0,2,Marketing,3810,Sim,3,2,0,0
20,90,36,Sim,Casado,Masculino,Cicero Dias,Saude,Pesquisador,9.0,3,Medicina,21777,Sim,1,0,0,0
21,163,31,Sim,Casado,Masculino,Genaro Rodrigues,Alimentos,Auditor,6.0,4,Ciencias Sociais,20739,Sim,7,7,7,0
22,261,35,Sim,Casado,Masculino,Marinheiro Dias,Saude,Diretor de Manufatura,23.0,2,Ciencias Sociais,15497,Sim,1,0,0,0
23,282,38,Sim,Casado,Masculino,Nathan Nunes,Saude,Representante da Saude,29.0,1,Medicina,11354,Sim,1,0,0,0
24,291,32,Sim,Casado,Masculino,Olavo Costa,Alimentos,Auditor,4.0,4,Medicina,25812,Nao,14,8,9,0
25,325,33,Sim,Casado,Masculino,Ranieri Nunes,Saude,Tecnico de Laboratorio,14.0,3,Medicina,22149,Sim,5,4,0,0
26,376,47,Sim,Casado,Masculino,Victor Barros,Saude,Gestor,29.0,4,Ciencias Sociais,10268,Sim,10,7,9,0
27,433,52,Sim,Casado,Masculino,Bernardo Jose Ferreira,Saude,Pesquisador,8.0,4,Medicina,17747,Nao,8,2,7,0
28,492,40,Sim,Casado,Masculino,Edmilson Costa,Alimentos,Auditor,22.0,2,Marketing,6110,Sim,6,4,1,0
29,582,33,Sim,Casado,Masculino,Joaquim Nunes,Saude,Gestor,15.0,1,Medicina,24619,Sim,7,6,7,0
30,587,31,Sim,Casado,Masculino,Jose Roberto Barros,Saude,Representante da Saude,20.0,3,Ciencias Sociais,22908,Nao,1,0,0,0
31,631,32,Sim,Casado,Masculino,Enzo Nunes,Alimentos,Auditor,11.0,4,Outros,23914,Nao,4,2,1,0
32,723,50,Sim,Casado,Masculino,Gael Rodrigues,Alimentos,Auditor,8.0,2,Formacao Tecnica,23452,Sim,4,3,1,0
33,787,55,Sim,Casado,Masculino,Gael Barros,Saude,Gestor,2.0,3,Medicina,21199,Sim,5,2,1,0
34,932,39,Sim,Casado,Masculino,Gael Nunes,Saude,Tecnico de Laboratorio,6.0,3,Medicina,4303,Sim,2,2,2,0
35,967,36,Sim,Casado,Masculino,Nicolas Teixeira,Alimentos,Auditor,3.0,1,Ciencias Sociais,5518,Sim,16,7,3,0
36,970,37,Sim,Casado,Masculino,Otavio Dias,Alimentos,Auditor,1.0,4,Ciencias Sociais,14922,Nao,14,1,11,0
37,1081,51,Sim,Casado,Masculino,Miguel Martins,Saude,Pesquisador,4.0,4,Ciencias Sociais,10332,Sim,10,0,2,0
38,1098,44,Sim,Casado,Masculino,Ravi Silva,Medicamentos,Tecnico de TI,1.0,2,Medicina,2326,Nao,20,6,3,0
39,1160,31,Sim,Casado,Masculino,Ravi Oliveira,Saude,Tecnico de Laboratorio,15.0,3,Medicina,6233,Nao,2,2,2,0
40,1309,32,Sim,Casado,Masculino,Heitor Dias,Saude,Tecnico de Laboratorio,7.0,2,Ciencias Sociais,22845,Nao,10,4,1,0
41,1333,44,Sim,Casado,Masculino,Valentin Martins,Saude,Tecnico de Laboratorio,3.0,3,Ciencias Sociais,14669,Nao,3,2,1,0
42,1389,31,Sim,Casado,Masculino,Lorenzo Barros,Saude,Diretor de Manufatura,22.0,4,Medicina,21057,Sim,10,2,6,0
43,1464,31,Sim,Casado,Masculino,Ravi Rodrigues,Saude,Tecnico de Laboratorio,2.0,3,Ciencias Sociais,21081,Sim,2,2,2,0
44,1573,38,Sim,Casado,Masculino,Miguel Teixeira,Saude,Diretor de Manufatura,2.0,3,Medicina,7653,Nao,5,2,1,0
45,1639,35,Sim,Casado,Masculino,Henrique Ferreira,Alimentos,Auditor,10.0,3,Medicina,21530,Nao,13,12,6,0
46,1716,47,Sim,Casado,Masculino,Nicolas Teixeira,Alimentos,Auditor,9.0,3,Ciencias Sociais,24164,Nao,23,5,14,0
47,1761,31,Sim,Casado,Masculino,Miguel Martins,Alimentos,Auditor,16.0,4,Marketing,19002,Nao,1,0,0,0
48,1767,43,Sim,Casado,Masculino,Ravi Santos,Saude,Pesquisador,17.0,3,Formacao Tecnica,15587,Sim,1,0,0,0
49,1807,34,Sim,Casado,Masculino,Caio Mendes,Saude,Tecnico de Laboratorio,9.0,4,Ciencias Sociais,6208,Nao,7,1,0,0
50,1842,31,Sim,Casado,Masculino,Ravi Rodrigues,Medicamentos,Tecnico de TI,18.0,5,Recursos Humanos,21495,Nao,1,0,0,0
51,1905,34,Sim,Casado,Masculino,Gabriel Oliveira,Saude,Pesquisador,16.0,4,Formacao Tecnica,14460,Sim,5,2,3,0
52,1967,31,Sim,Casado,Masculino,Pedro Santos,Alimentos,Auditor,26.0,4,Marketing,21075,Sim,10,7,0,0
53,2032,56,Sim,Casado,Masculino,Pedro Barros,Saude,Tecnico de Laboratorio,7.0,2,Formacao Tecnica,3666,Nao,10,9,9,0

In [40]:
#Atribuindo valor à nova coluna - exemplo
base_filtrada['coluna_nova'] = 0

<ipython-input-40-8bf98bcc90c2>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base_filtrada['coluna_nova'] = 0

In [41]:
base_filtrada

,IDCOLABORADOR,IDADE,INSATISTFEITO,STATUSCIVIL,GENERO,NOME,SETOR,CARGO,CEP,NIVELEDUCACAO,FORMACAO,RENDAMENSAL,DESCONTOULTIMAFATURA,ANONAEMPRESA,ANOSMESMAPOSICAO,ANOSDESDEULTIMAPROMOCAO,coluna_nova
0,58,10,Sim,Casado,Feminino,Priscila Pereira,Saude,Diretor de Pesquisa,12.0,3,Formacao Tecnica,16280,Nao,22,15,15,0
1,161,10,Sim,Casado,Feminino,Vanessa Carvalho,Saude,Pesquisador,14.0,4,Ciencias Sociais,4510,Sim,5,4,4,0
2,165,10,Sim,Casado,Feminino,Amanda Goncalves,Saude,Representante da Saude,23.0,4,Medicina,3465,Nao,40,10,15,0
3,175,10,Sim,Casado,Feminino,Ana Pereira,Alimentos,Auditor,20.0,3,Ciencias Sociais,24788,Sim,2,2,2,0
4,328,10,Sim,Casado,Feminino,Patricia Oliveira,Saude,Tecnico de Laboratorio,2.0,2,Ciencias Sociais,21509,Nao,9,7,1,0
5,445,10,Sim,Casado,Feminino,Tatiane Carvalho,Alimentos,Auditor,3.0,2,Medicina,17778,Sim,1,0,0,0
6,684,10,Sim,Casado,Feminino,Fernanda Costa,Alimentos,Auditor,26.0,4,Ciencias Sociais,5630,Nao,1,1,0,0
7,840,10,Sim,Casado,Feminino,Bruna Almeida,Alimentos,Auditor,11.0,3,Marketing,5860,Nao,9,8,7,0
8,1033,10,Sim,Casado,Feminino,Leticia Oliveira,Saude,Representante da Saude,11.0,2,Medicina,14382,Nao,1,0,0,0
9,1038,10,Sim,Casado,Feminino,Valentina Martins,Alimentos,Gestor,2.0,1,Marketing,25846,Nao,32,14,6,0
10,1295,10,Sim,Casado,Feminino,Fernanda Alves,Saude,Representante da Saude,15.0,3,Medicina,14075,Nao,10,7,0,0
11,1360,10,Sim,Casado,Feminino,Priscila Pereira,Saude,Diretor de Manufatura,7.0,4,Medicina,12023,Sim,10,9,5,0
12,1380,10,Sim,Casado,Feminino,Daniela Silva,Alimentos,Auditor,18.0,4,Marketing,23288,Sim,4,2,3,0
13,1467,10,Sim,Casado,Feminino,Luana Almeida,Medicamentos,Tecnico de TI,9.0,4,Formacao Tecnica,3072,Nao,2,2,2,0
14,1572,10,Sim,Casado,Feminino,Rafaela Santos,Saude,Diretor de Manufatura,2.0,5,Formacao Tecnica,14618,Nao,33,7,1,0
15,1691,10,Sim,Casado,Feminino,Michele Almeida,Alimentos,Representante de Setor,7.0,2,Medicina,11740,Sim,9,7,7,0
16,1821,10,Sim,Casado,Feminino,Luana Oliveira,Saude,Representante da Saude,21.0,2,Medicina,10842,Nao,9,7,3,0
17,1869,10,Sim,Casado,Feminino,Priscila Pereira,Alimentos,Auditor,10.0,3,Ciencias Sociais,14011,Nao,8,7,0,0
18,42,10,Sim,Casado,Masculino,Anselmo Souza,Alimentos,Representante de Setor,NaN,3,Formacao Tecnica,3335,Nao,1,0,0,0
19,47,10,Sim,Casado,Masculino,Antônio Oliveira,Alimentos,Representante de Setor,3.0,2,Marketing,3810,Sim,3,2,0,0
20,90,10,Sim,Casado,Masculino,Cicero Dias,Saude,Pesquisador,9.0,3,Medicina,21777,Sim,1,0,0,0
21,163,10,Sim,Casado,Masculino,Genaro Rodrigues,Alimentos,Auditor,6.0,4,Ciencias Sociais,20739,Sim,7,7,7,0
22,261,10,Sim,Casado,Masculino,Marinheiro Dias,Saude,Diretor de Manufatura,23.0,2,Ciencias Sociais,15497,Sim,1,0,0,0
23,282,10,Sim,Casado,Masculino,Nathan Nunes,Saude,Representante da Saude,29.0,1,Medicina,11354,Sim,1,0,0,0
24,291,10,Sim,Casado,Masculino,Olavo Costa,Alimentos,Auditor,4.0,4,Medicina,25812,Nao,14,8,9,0
25,325,10,Sim,Casado,Masculino,Ranieri Nunes,Saude,Tecnico de Laboratorio,14.0,3,Medicina,22149,Sim,5,4,0,0
26,376,10,Sim,Casado,Masculino,Victor Barros,Saude,Gestor,29.0,4,Ciencias Sociais,10268,Sim,10,7,9,0
27,433,10,Sim,Casado,Masculino,Bernardo Jose Ferreira,Saude,Pesquisador,8.0,4,Medicina,17747,Nao,8,2,7,0
28,492,10,Sim,Casado,Masculino,Edmilson Costa,Alimentos,Auditor,22.0,2,Marketing,6110,Sim,6,4,1,0
29,582,10,Sim,Casado,Masculino,Joaquim Nunes,Saude,Gestor,15.0,1,Medicina,24619,Sim,7,6,7,0
30,587,10,Sim,Casado,Masculino,Jose Roberto Barros,Saude,Representante da Saude,20.0,3,Ciencias Sociais,22908,Nao,1,0,0,0
31,631,10,Sim,Casado,Masculino,Enzo Nunes,Alimentos,Auditor,11.0,4,Outros,23914,Nao,4,2,1,0
32,723,10,Sim,Casado,Masculino,Gael Rodrigues,Alimentos,Auditor,8.0,2,Formacao Tecnica,23452,Sim,4,3,1,0
33,787,10,Sim,Casado,Masculino,Gael Barros,Saude,Gestor,2.0,3,Medicina,21199,Sim,5,2,1,0
34,932,10,Sim,Casado,Masculino,Gael Nunes,Saude,Tecnico de Laboratorio,6.0,3,Medicina,4303,Sim,2,2,2,0
35,967,10,Sim,Casado,Masculino,Nicolas Teixeira,Alimentos,Auditor,3.0,1,Ciencias Sociais,5518,Sim,16,7,3,0
36,970,10,Sim,Casado,Masculino,Otavio Dias,Alimentos,Auditor,1.0,4,Ciencias Sociais,14922,Nao,14,1,11,0
37,1081,10,Sim,Casado,Masculino,Miguel Martins,Saude,Pesquisador,4.0,4,Ciencias Sociais,10332,Sim,10,0,2,0
38,1098,10,Sim,Casado,Masculino,Ravi Silva,Medicamentos,Tecnico de TI,1.0,2,Medicina,2326,Nao,20,6,3,0
39,1160,10,Sim,Casado,Masculino,Ravi Oliveira,Saude,Tecnico de Laboratorio,15.0,3,Medicina,6233,Nao,2,2,2,0
40,1309,10,Sim,Casado,Masculino,Heitor Dias,Saude,Tecnico de Laboratorio,7.0,2,Ciencias Sociais,22845,Nao,10,4,1,0
41,1333,10,Sim,Casado,Masculino,Valentin Martins,Saude,Tecnico de Laboratorio,3.0,3,Ciencias Sociais,14669,Nao,3,2,1,0
42,1389,10,Sim,Casado,Masculino,Lorenzo Barros,Saude,Diretor de Manufatura,22.0,4,Medicina,21057,Sim,10,2,6,0
43,1464,10,Sim,Casado,Masculino,Ravi Rodrigues,Saude,Tecnico de Laboratorio,2.0,3,Ciencias Sociais,21081,Sim,2,2,2,0
44,1573,10,Sim,Casado,Masculino,Miguel Teixeira,Saude,Diretor de Manufatura,2.0,3,Medicina,7653,Nao,5,2,1,0
45,1639,10,Sim,Casado,Masculino,Henrique Ferreira,Alimentos,Auditor,10.0,3,Medicina,21530,Nao,13,12,6,0
46,1716,10,Sim,Casado,Masculino,Nicolas Teixeira,Alimentos,Auditor,9.0,3,Ciencias Sociais,24164,Nao,23,5,14,0
47,1761,10,Sim,Casado,Masculino,Miguel Martins,Alimentos,Auditor,16.0,4,Marketing,19002,Nao,1,0,0,0
48,1767,10,Sim,Casado,Masculino,Ravi Santos,Saude,Pesquisador,17.0,3,Formacao Tecnica,15587,Sim,1,0,0,0
49,1807,10,Sim,Casado,Masculino,Caio Mendes,Saude,Tecnico de Laboratorio,9.0,4,Ciencias Sociais,6208,Nao,7,1,0,0
50,1842,10,Sim,Casado,Masculino,Ravi Rodrigues,Medicamentos,Tecnico de TI,18.0,5,Recursos Humanos,21495,Nao,1,0,0,0
51,1905,10,Sim,Casado,Masculino,Gabriel Oliveira,Saude,Pesquisador,16.0,4,Formacao Tecnica,14460,Sim,5,2,3,0
52,1967,10,Sim,Casado,Masculino,Pedro Santos,Alimentos,Auditor,26.0,4,Marketing,21075,Sim,10,7,0,0
53,2032,10,Sim,Casado,Masculino,Pedro Barros,Saude,Tecnico de Laboratorio,7.0,2,Formacao Tecnica,3666,Nao,10,9,9,0